server {
    listen 80;
    server_name _;

    location ~ /\.(env|git|ht|svn|bak) {
        deny all;
    }

    # Next.js frontend
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Correlation-ID $request_id;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # NestJS API
    location /api {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://localhost:3001;
        # Indispensables para CORS y Auth
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Correlation-ID $request_id;
    }

    # Security headers
    add_header X-Request-ID $request_id always;
}